name: Cache Action
on:
  workflow_dispatch:
  schedule:
    - cron: 0 */4 * * * # Every 4 hours, change it accordingly

jobs:
  stats:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Stats Card
    steps:
      - uses: actions/checkout@v3
        name: Check out current commit
      - uses: suisei-cn/actions-download-file@v1.3.0
        id: stats
        name: Download the stats file
        with:
          url: "https://github-stats-navalkumar007.vercel.app/api?username=navalkumar007&rank_icon=github&hide=stars,issues&theme=gotham&hide_border=true&include_all_commits=true&count_private=true" # Put your own vercel instance URL here
          target: grs
          filename: stats.svg # Need to have the file name prepared as svg
      - uses: actions/upload-artifact@master
        with:
          name: stats
          path: grs

  langs:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Langs Card
    steps:
      - uses: actions/checkout@v3
        name: Check out current commit
      - uses: suisei-cn/actions-download-file@v1.3.0
        id: langs
        name: Download the langs file
        with:
          url: "https://github-stats-navalkumar007.vercel.app/api/top-langs/?username=navalkumar007&theme=gotham&hide_border=true&include_all_commits=true&count_private=true&layout=compact" # Put your own vercel instance URL here
          target: grs
          filename: langs.svg # Need to have the file name prepared as svg
      - uses: actions/upload-artifact@master
        with:
          name: langs
          path: grs
          
          
  streaks:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Streaks Card
    steps:
      - uses: actions/checkout@v3
        name: Check out current commit
      - uses: suisei-cn/actions-download-file@v1.3.0
        id: streak
        name: Download the streaks file
        with:
          url: "https://github-readme-streak-stats.herokuapp.com/?user=navalkumar007&include_all_commits=true&count_private=true&theme=gotham&hide_border=true" # Put your own vercel instance URL here
          target: grs
          filename: streaks.svg # Need to have the file name prepared as svg
      - uses: actions/upload-artifact@master
        with:
          name: streaks
          path: grs

  pushstats:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Push Stats
    needs: [stats] # Put any jobs (card) needed here before we push
    steps:
      - uses: actions/download-artifact@master
        with:
          name: stats
          path: grs
      - name: Push
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: resource/grs # May change to your desired branch name, the final URL need to be updated if you change this
          build_dir: grs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pushlangs:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Push Langs
    needs: [langs] # Put any jobs (card) needed here before we push
    steps:
      - uses: actions/download-artifact@master
        with:
          name: langs
          path: grs
      - name: Push
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: resource/lang # May change to your desired branch name, the final URL need to be updated if you change this
          build_dir: grs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  pushstreaks:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Push Streaks
    needs: [streaks] # Put any jobs (card) needed here before we push
    steps:
      - uses: actions/download-artifact@master
        with:
          name: streaks
          path: grs
      - name: Push
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: resource/streaks # May change to your desired branch name, the final URL need to be updated if you change this
          build_dir: grs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
